# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unison' do
  use_frameworks!
  
  # UI
  pod 'SnapKit', '~> 5.0.0'
  
  # Logging
  pod 'SwiftyBeaver'

end
