#
#  .swiftlint.yml
#  Inwellen
#
#  Created by Dzmitry Shuysky on 9.07.21.
#  Copyright © 2021 Inwellen. All rights reserved.
#

included:
  - Reusable
  - Groups
  - Core
  - Inwellen
  
excluded:
  - Pods

disabled_rules:
  - private_over_fileprivate
  - switch_case_alignment
  - trailing_whitespace
  - inclusive_language
  - identifier_name
  - type_name
  - nesting

opt_in_rules:
  - weak_delegate
  - anyobject_protocol
  - capture_variable
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - function_default_parameter_at_end
  - identical_operands
  - last_where
  - modifier_order
  - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - unneeded_break_in_switch
  - unused_import
  - yoda_condition

function_body_length:
  warning: 40

line_length:
  warning: 100
  ignores_comments: true

file_length:
  warning: 300

enum_case_associated_values_count:
  warning: 5

force_cast:
  severity: warning

force_try:
  severity: warning
