platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Inwellen' do
  
  # UI
  pod 'SnapKit', '~> 5.0.0'

  # Linter
  pod 'SwiftLint'
  
  # Logging
  pod 'SwiftyBeaver'

  # MARK: -
  # MARK: - Testing

  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'InwellenTests' do
    inherit! :search_paths
    testing_pods
  end

end
