# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Inwellen' do
  use_frameworks!
  
  # UI
  pod 'SnapKit', '~> 5.0.0'

  # Linter
  pod 'SwiftLint'
  
  # Logging
  pod 'SwiftyBeaver'

end
